id: sleeplens_pipeline
namespace: com.sleeplens
inputs:
  - id: date
    type: STRING
    defaults: "2026-01-21"

triggers:
  - id: daily_schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"


tasks:
  - id: generate_data
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/muratkahraman/Downloads/sleeplens/sleeplens:/project
    commands:
      - docker compose -f /project/docker/docker-compose.yml run --rm spark python3 ingestion/extract/fetch_public_summary.py --date {{ inputs.date }}

  - id: upload_to_snowflake
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/muratkahraman/Downloads/sleeplens/sleeplens:/project
    commands:
      - docker compose -f /project/docker/docker-compose.yml run --rm --entrypoint python3 dbt /app/ingestion/load/upload_to_snowflake.py --date {{ inputs.date }}


  - id: dbt_run
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/muratkahraman/Downloads/sleeplens/sleeplens:/project
    commands:
      - docker compose -f /project/docker/docker-compose.yml run --rm dbt run


  - id: dbt_test
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/muratkahraman/Downloads/sleeplens/sleeplens:/project
    commands:
      - docker compose -f /project/docker/docker-compose.yml run --rm dbt test

